# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asm68 < Formula
  desc "m68k assembler (asm68)"
  homepage "https://github.com/Urethramancer/m68k"
  version "0.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_darwin_amd64.tar.gz"
      sha256 "95d5ebfa9793402185a66430696f2ac180aa31600797bc32e27df6aefbf7e803"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_darwin_arm64.tar.gz"
      sha256 "24ef7920ae0a6e4217383e4971b7f5c3b87da4fe8dbd0e461ec0ae7b52234785"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_linux_amd64.tar.gz"
      sha256 "604d703aa65d29e979f3c604f0d23bb73d0687d4f91f1e09c9e8f4a52ebf2eb1"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_linux_arm64.tar.gz"
      sha256 "dac5c2441843b2e4c5f4d6c6311c5749e241a9a878a684db7f498fe22df9d993"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end
end
