# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsec < Formula
  desc "Store secrets in AWS Parameter Store."
  homepage "https://github.com/grimdork/awsec"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/awsec/releases/download/v0.11.2/awsec_0.11.2_Darwin_x86_64.tar.xz"
      sha256 "4f30d3ddca7712212bdf96e0a50dc53811207e02167223af525df930a09a8dde"

      def install
        bin.install "awsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/awsec/releases/download/v0.11.2/awsec_0.11.2_Darwin_arm64.tar.xz"
      sha256 "3be8936974b764b5102d6dfcc244584a92b947e5ba8f4a7b90a179d497630949"

      def install
        bin.install "awsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/awsec/releases/download/v0.11.2/awsec_0.11.2_Linux_x86_64.tar.xz"
      sha256 "da591ee3652f88a43eb782b2361d98dbdf5bbac5017b1b86a44a32b8f458ccad"

      def install
        bin.install "awsec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/awsec/releases/download/v0.11.2/awsec_0.11.2_Linux_arm64.tar.xz"
      sha256 "010d3e370efe9ed6199309897f6f6da25a77538e379598d9bbe9cb7fe53225bc"

      def install
        bin.install "awsec"
      end
    end
  end
end
