# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dis68 < Formula
  desc "m68k disassembler (dis68)"
  homepage "https://github.com/Urethramancer/m68k"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.6.0/m68k_0.6.0_darwin_amd64.tar.gz"
      sha256 "9eafe801796dfb70c407d7ac92f8bcfc49a7e84db59be771e33edb4d12ebcbaa"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.6.0/m68k_0.6.0_darwin_arm64.tar.gz"
      sha256 "1593d083eb76aecbe1391adb8a47535a19b3870985fc7e38f13f39a23a15557b"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.6.0/m68k_0.6.0_linux_amd64.tar.gz"
      sha256 "25722e4425b694db06c2954547e441fd31d9d6779a516240fcdd330100435228"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.6.0/m68k_0.6.0_linux_arm64.tar.gz"
      sha256 "fa804be0a3c6d22aadc674c60f973a73d1e60243b970ab2dc88425db1c6136f2"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end
end
