# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dis68 < Formula
  desc "m68k disassembler (dis68)"
  homepage "https://github.com/Urethramancer/m68k"
  version "0.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_darwin_amd64.tar.gz"
      sha256 "dae01593b843a8db298d1ada274d312977bafab57faf1574280fa7756e5a0ecd"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_darwin_arm64.tar.gz"
      sha256 "a2d630be3bd513e7c8847dfa4c66a9c2a1bb308904fc360e34dcc3282ab41ab6"

      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_linux_amd64.tar.gz"
      sha256 "fb6febf50cf88ed88fed1119d6f2bc182317587aa033029c0313c57aac4b41d9"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Urethramancer/m68k/releases/download/v0.5.5/m68k_0.5.5_linux_arm64.tar.gz"
      sha256 "01505f1abe4d92e9b5b0f610e1f017dd3afbf7f8458c5990041ace0acfdceba6"
      define_method(:install) do
        bin.install "asm68"
        bin.install "dis68"
      end
    end
  end
end
