# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foreman < Formula
  desc "Store secrets in AWS Parameter Store."
  homepage "https://github.com/grimdork/awsec"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Darwin_arm64.tar.xz"
      sha256 "a208089ba7a9209a8a1225684de5da5ebbfd59485ec70627afb71375a1f0e942"

      def install
        bin.install "foreman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Darwin_x86_64.tar.xz"
      sha256 "9b9e9e13a1162a68f8e7d4f6e2e3360b1a6b0c3280d03ce7a5d5ceab4d19b923"

      def install
        bin.install "foreman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Linux_arm64.tar.xz"
      sha256 "960279c799b26a9583e309eb3b10142e1791647e54a7de4c7a60db02137899eb"

      def install
        bin.install "foreman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Linux_x86_64.tar.xz"
      sha256 "3f73bad8fd7552759e42f8d04d99e14ff0dcb793b918da0876393d2930f124f8"

      def install
        bin.install "foreman"
      end
    end
  end
end
