# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foreman < Formula
  desc "Store secrets in AWS Parameter Store."
  homepage "https://github.com/grimdork/awsec"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Darwin_arm64.tar.xz"
      sha256 "7f9e7db2a9dd64e1238dc1a9742c032f7561b079aa7305cd4878a6c83431a92c"

      def install
        bin.install "foreman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Darwin_x86_64.tar.xz"
      sha256 "4a359b1e83287763a89904462dbbb53fb43a8881d5011c4b7d6d43f19bb37a6f"

      def install
        bin.install "foreman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Linux_x86_64.tar.xz"
      sha256 "00536d0abc3cb06fda859cdf7f430e45332e84e2adc721b28b9c1620cb9d1381"

      def install
        bin.install "foreman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/foreman/releases/download/v0.1.0/foreman_0.1.0_Linux_arm64.tar.xz"
      sha256 "4744383749b69bb50af6930ff7e718766790693c3cc5c9cdab6588dfd06fd1d9"

      def install
        bin.install "foreman"
      end
    end
  end
end
