# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kush < Formula
  desc "kush — small interactive shell"
  homepage "https://github.com/grimdork/kush"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/grimdork/kush/releases/download/v0.3.0/kush_0.3.0_darwin_arm64.tar.gz"
    sha256 "6c57f9d4a9fa39cebd09e31c0506a425c347f537599d12b23a6f54632d739270"

    define_method(:install) do
      bin.install "kush"
    end
  end

  test do
    system "#{bin}/kush", "--version"
  end
end
