# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kush < Formula
  desc "kush — small interactive shell"
  homepage "https://github.com/grimdork/kush"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/grimdork/kush/releases/download/v0.3.0/kush_0.3.0_darwin_arm64.tar.gz"
    sha256 "9658cbb6a5556757b611dff71c570cd3fdf26b6199e0d164474d2b810e2ee3ca"

    define_method(:install) do
      bin.install "kush"
    end
  end

  test do
    system "#{bin}/kush", "--version"
  end
end
