# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Name < Formula
  desc "Small utility for path/name manipulation"
  homepage "https://github.com/grimdork/name"
  version "1.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/name/releases/download/v1.1.5/name_1.1.5_darwin_amd64.tar.gz"
      sha256 "4595edd77d81965f569009e7a1ddf988f719b316492c98ee6ff3a3535eb90fe2"

      define_method(:install) do
        bin.install "name"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/name/releases/download/v1.1.5/name_1.1.5_darwin_arm64.tar.gz"
      sha256 "9ff73bbde2f241836724c568cabbe1c0b735d5c77e4e257532dd75189bdb4c75"

      define_method(:install) do
        bin.install "name"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/name/releases/download/v1.1.5/name_1.1.5_linux_amd64.tar.gz"
      sha256 "4e4b5ff63df0426702f952dbafac3c1e1dad1686934b9ec50dff06850c8dcb20"
      define_method(:install) do
        bin.install "name"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/name/releases/download/v1.1.5/name_1.1.5_linux_arm64.tar.gz"
      sha256 "94db4c04afd5cf8469ddced5c3fd43381327143e574a19bf7f85b6287a0daeca"
      define_method(:install) do
        bin.install "name"
      end
    end
  end
end
