# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwgen < Formula
  desc "A password generator with a few different variations."
  homepage "https://github.com/grimdork/pwgen"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/pwgen/releases/download/v1.0.1/pwgen_1.0.1_Darwin_x86_64.tar.xz"
      sha256 "283c675d9675bd1e0ae884a87ec841b0db40085983af39044bd769bc46929547"

      def install
        bin.install "pwgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/pwgen/releases/download/v1.0.1/pwgen_1.0.1_Darwin_arm64.tar.xz"
      sha256 "cadc55c30909f1c791ef403d7479055fab770579da704d1cbd518f04f7b743f9"

      def install
        bin.install "pwgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/pwgen/releases/download/v1.0.1/pwgen_1.0.1_Linux_arm64.tar.xz"
      sha256 "e1c847edec1692447cc12afcd5d1bd7203261ea4beb7ce4c0cddda7f7e144959"

      def install
        bin.install "pwgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/pwgen/releases/download/v1.0.1/pwgen_1.0.1_Linux_x86_64.tar.xz"
      sha256 "beda5117373c7a415c8bd5f8ac75d981cd7da63b2a5e16f901e564f82ea1d203"

      def install
        bin.install "pwgen"
      end
    end
  end
end
