# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3 < Formula
  desc "Simpler S3 commands with support for web protocols and SSH."
  homepage "https://github.com/grimdork/s3"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/s3/releases/download/v0.2.6/s3_Darwin_arm64.tar.xz"
      sha256 "5a0707cc9cf2c02c399271d8db2f8181fe712b2cf1e4875214e7c328d6e1f7d1"

      def install
        bin.install "s3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/s3/releases/download/v0.2.6/s3_Darwin_x86_64.tar.xz"
      sha256 "fe3aafa807fff5c622814ed575602f659cee08dc6d8d2ef09ff878840aa26100"

      def install
        bin.install "s3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/s3/releases/download/v0.2.6/s3_Linux_arm64.tar.xz"
      sha256 "54adeda5f4a0c70b994b6256ac8f304984a8ee021f90c33e57898b3d7c068c1f"

      def install
        bin.install "s3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/s3/releases/download/v0.2.6/s3_Linux_x86_64.tar.xz"
      sha256 "1e55179f8aa7c7e411a8bf7c62548439d226386947f3a4645fdf5dd90acd41b7"

      def install
        bin.install "s3"
      end
    end
  end
end
