# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3 < Formula
  desc "Simpler S3 commands with support for web protocols and SSH."
  homepage "https://github.com/grimdork/s3"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/s3/releases/download/v0.2.7/s3_Darwin_arm64.tar.xz"
      sha256 "35fa4a15457bbdbcec7cab65e3ca74055fe974dabc0bbb23064c8f3368a66bc3"

      def install
        bin.install "s3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/s3/releases/download/v0.2.7/s3_Darwin_x86_64.tar.xz"
      sha256 "96c53302538c98e4eec1a0ae23ac890ceaa3a94c6c4c18f634b6eb8fa18f0354"

      def install
        bin.install "s3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/s3/releases/download/v0.2.7/s3_Linux_arm64.tar.xz"
      sha256 "ea5727f95c8d70ed7c8c797a6402b99d7c94dea98941b08b3a7754408e0604c3"

      def install
        bin.install "s3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/s3/releases/download/v0.2.7/s3_Linux_x86_64.tar.xz"
      sha256 "af72a4bea9a222e0488145ee19ab3ef0cf727856ecd6870b90671c45c9a9e19d"

      def install
        bin.install "s3"
      end
    end
  end
end
