# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sec < Formula
  desc "Store secrets in AWS Parameter Store."
  homepage "https://github.com/grimdork/sec"
  version "0.7.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/sec/releases/download/v0.7.6/sec_0.7.6_Darwin_x86_64.zip"
      sha256 "c898f9e58893b7ef946924a179b97cfcc7d1efbea16cdbcca2a465f762c9e24c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/grimdork/sec/releases/download/v0.7.6/sec_0.7.6_Darwin_arm64.zip"
      sha256 "e3af61c70d0d4b4aa1b7ee124d9c4386b277c45f11012924c57c2d590e30a14e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grimdork/sec/releases/download/v0.7.6/sec_0.7.6_Linux_x86_64.tar.gz"
      sha256 "5aa649575fdd467684e820f3ffca90f4413fced00e75e540a57af31ed4487414"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grimdork/sec/releases/download/v0.7.6/sec_0.7.6_Linux_arm64.tar.gz"
      sha256 "17871483a5526a26917496c6b0de35dc99fa2b902ac842c3f9b669e1b7edb0bc"
    end
  end

  def install
    bin.install "sec"
  end
end
