# This file was generated by GoReleaser. DO NOT EDIT.
cask "kush" do
  name "kush"
  desc "Kubernetes utility shell"
  homepage "https://github.com/grimdork/kush"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kush"

  on_macos do
    on_arm do
      url "https://github.com/grimdork/kush/releases/download/v#{version}/kush_#{version}_darwin_arm64.tar.gz"
      sha256 "95675fe7625d27977e3c2c16a998fff89522e4d1a82084ff21a80958b9b7018e"
      rename "kush_0.3.0_darwin_arm64/kush", "kush"
    end
  end

  # No zap stanza required
end
