# This file was generated by GoReleaser. DO NOT EDIT.
cask "kush" do
  name "kush"
  desc "Kubernetes utility shell"
  homepage "https://github.com/grimdork/kush"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kush"

  on_macos do
    on_arm do
      url "https://github.com/grimdork/kush/releases/download/v#{version}/kush_#{version}_darwin_arm64.tar.gz"
      sha256 "9658cbb6a5556757b611dff71c570cd3fdf26b6199e0d164474d2b810e2ee3ca"
      rename "kush_0.3.0_darwin_arm64/kush", "kush"
    end
  end

  # No zap stanza required
end
